"""empty message

Revision ID: 0101849b8117
Revises: c9e410346751
Create Date: 2023-04-13 11:44:27.450980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0101849b8117'
down_revision = 'c9e410346751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user'], ['id'])
        batch_op.drop_column('customer')

    # ### end Alembic commands ###
